"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { slugify } from "@/lib/utils";

export async function saveProduct(formData:FormData){await requireAdmin();const db=createAdminSupabaseClient();const id=String(formData.get('id')||'');const title=String(formData.get('title')||'').trim();const data={title,slug:slugify(String(formData.get('slug')||title)),description:String(formData.get('description')||''),short_description:String(formData.get('short_description')||'')||null,regular_price_cents:Math.round(Number(formData.get('regular_price')||0)*100),sale_price_cents:formData.get('sale_price')?Math.round(Number(formData.get('sale_price'))*100):null,product_kind:String(formData.get('product_kind'))==='kit'?'kit':'individual',status:String(formData.get('status'))==='published'?'published':'draft',grade_level:String(formData.get('grade_level')||'')||null,material_type:String(formData.get('material_type')||'')||null,tags:String(formData.get('tags')||'').split(',').map(v=>v.trim()).filter(Boolean),published_at:String(formData.get('status'))==='published'?new Date().toISOString():null};if(!title||!data.description)throw new Error('Título e descrição são obrigatórios.');const result=id?await db.from('products').update(data).eq('id',id).select('id').single():await db.from('products').insert(data).select('id').single();if(result.error||!result.data)throw new Error(result.error?.message||'Não foi possível salvar o produto.');const categoryIds=String(formData.get('category_ids')||'').split(',').filter(Boolean);await db.from('product_categories').delete().eq('product_id',result.data.id);if(categoryIds.length)await db.from('product_categories').insert(categoryIds.map(category_id=>({product_id:result.data!.id,category_id})));const kitIds=String(formData.get('kit_items')||'').split(',').filter(Boolean);if(data.product_kind==='kit'){await db.from('kit_items').delete().eq('kit_product_id',result.data.id);if(kitIds.length)await db.from('kit_items').insert(kitIds.map((included_product_id,sort_order)=>({kit_product_id:result.data!.id,included_product_id,sort_order})));}revalidatePath('/admin/produtos');revalidatePath('/produtos');redirect(`/admin/produtos/${result.data.id}`);}
export async function archiveProduct(formData:FormData){await requireAdmin();const id=String(formData.get('id'));await createAdminSupabaseClient().from('products').update({status:'archived'}).eq('id',id);revalidatePath('/admin/produtos');revalidatePath('/produtos');}
