import { requireUser } from "@/lib/auth";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { StorefrontFooter, StorefrontHeader } from "@/components/Storefront";
import { DownloadButton } from "@/components/DownloadButton";
import Link from "next/link";
import { formatDate } from "@/lib/utils";

export const dynamic = "force-dynamic";
export default async function MyPurchasesPage() { const profile=await requireUser(); const supabase=await createServerSupabaseClient(); const { data }=await supabase.from("purchases").select("id,granted_at,status,products(id,title,slug,cover_path),order_items(orders(order_number,status,created_at))").eq("user_id",profile.id).eq("status","active").order("granted_at",{ascending:false}); const rows=(data??[]) as unknown as Array<{id:string;granted_at:string;products:{id:string;title:string;slug:string;cover_path:string|null}|null;order_items:{orders:{order_number:string;status:string;created_at:string}|null}|null}>; return <><StorefrontHeader isAdmin={profile.role === "admin"}/><main className="page container"><p className="eyebrow">Sua biblioteca</p><h1 style={{ marginTop:14,fontSize:"clamp(42px,6vw,66px)" }}>Minhas Compras</h1><p className="lead">Olá, {profile.name || "professora"}. Aqui ficam seus materiais liberados para baixar sempre que precisar.</p>{!rows.length?<div className="empty">Você ainda não tem materiais liberados. <Link className="link" href="/produtos">Explorar materiais</Link></div>:<div className="stack">{rows.map((row)=><article className="panel cart-line" key={row.id}><div className="art-mini"/><div style={{flex:1}}><span className="eyebrow">Pedido {row.order_items?.orders?.order_number ?? ""}</span><h2 style={{fontSize:24,marginTop:8}}>{row.products?.title}</h2><p style={{color:"var(--muted)",fontSize:13}}>Liberado em {formatDate(row.granted_at)} · Pedido aprovado</p></div>{row.products?<DownloadButton productId={row.products.id}/>:null}</article>)}</div>}</main><StorefrontFooter /></>; }
