import Link from "next/link";
import { listCatalog, listCategories } from "@/lib/catalog";
import { ProductCard } from "@/components/ProductCard";
import { StorefrontFooter, StorefrontHeader } from "@/components/Storefront";

export const dynamic = "force-dynamic";
export default async function HomePage() {
  const [products, categories] = await Promise.all([listCatalog({ limit: 8 }), listCategories()]);
  return <><StorefrontHeader /><main><section className="hero"><div className="container hero-grid"><div><span className="eyebrow">✦ Inglês brincando nos anos iniciais</span><h1 style={{ marginTop:18 }}>Pequenas descobertas.<br /><span style={{ textDecoration:"underline", textDecorationColor:"#ffd95b", textDecorationThickness:10 }}>Grandes aventuras.</span></h1><p className="lead">Atividades coloridas, jogos e materiais digitais para tornar o inglês dos anos iniciais mais leve, divertido e cheio de participação.</p><div className="row"><Link className="button" href="/produtos">Escolher uma atividade →</Link><a className="button secondary" href="#como-funciona">Como funciona</a></div><p style={{ fontSize:13,fontWeight:800,color:"#54706d",marginTop:24 }}>⇩ Pronto para imprimir &nbsp;&nbsp; ⊞ Feito para aprender brincando</p></div><div className="hero-art"><span className="eyebrow">Teacher Luana</span><div className="worksheet-row"><div className="worksheet"><small>FLASHCARDS</small><strong>1 · 2 · 3</strong></div><div className="worksheet"><small>MINI GAME</small><strong>Match!</strong></div></div><div style={{ border:"1px solid rgba(255,255,255,.35)",borderRadius:17,padding:16 }}><h2 style={{ fontSize:29 }}>Material que inspira.</h2><p style={{ marginBottom:0,color:"#d7f0e7" }}>Pronto para imprimir, brincar e aprender.</p></div></div></div></section><section className="section"><div className="container"><div className="section-heading"><div><p>Encontre seu caminho</p><h2>Materiais por categoria</h2></div><Link className="link" href="/produtos">Ver catálogo →</Link></div><div className="category-grid">{categories.map((category, index) => <Link key={category.id} className="category" href={`/categorias/${category.slug}`}><b>{["✦","◌","▣","☀","♧"][index % 5]}</b>{category.name}</Link>)}</div></div></section><ProductSection eyebrow="Selecionados para você" title="Materiais em destaque" products={products.slice(0,4)} /><ProductSection eyebrow="Acabou de chegar" title="Novidades para sua biblioteca" products={products.slice(4,8)} soft /><section id="como-funciona" className="section"><div className="container"><div className="section-heading"><div><p>Compra sem complicação</p><h2>Da descoberta ao arquivo, em poucos passos.</h2></div></div><div className="category-grid"><div className="category"><b>01</b>Escolha uma atividade</div><div className="category"><b>02</b>Finalize com segurança</div><div className="category"><b>03</b>Acesse Minhas Compras</div></div></div></section></main><StorefrontFooter /></>;
}
function ProductSection({ eyebrow, title, products, soft = false }: { eyebrow: string; title: string; products: Awaited<ReturnType<typeof listCatalog>>; soft?: boolean }) { return <section className={`section ${soft ? "soft" : ""}`}><div className="container"><div className="section-heading"><div><p>{eyebrow}</p><h2>{title}</h2></div><Link className="link" href="/produtos">Ver todos →</Link></div>{products.length ? <div className="product-grid">{products.map((product,index) => <ProductCard key={product.id} product={product} index={index} />)}</div> : <div className="empty">Configure o Supabase e execute o seed DEMO para ver os materiais aqui.</div>}</div></section>; }
