"use client";
import Link from "next/link";
import { useState } from "react";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";

export function AuthForm({ mode }: { mode: "login" | "signup" | "recovery" | "new-password" }) {
  const [name,setName] = useState(""); const [email,setEmail] = useState(""); const [password,setPassword] = useState(""); const [message,setMessage] = useState(""); const [error,setError] = useState(""); const [loading,setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault();setError("");setMessage("");setLoading(true); const supabase=createBrowserSupabaseClient();try { if (mode === "login") { const { error }=await supabase.auth.signInWithPassword({email,password}); if(error) throw error; window.location.assign("/minhas-compras"); return; } if (mode === "signup") { const { error }=await supabase.auth.signUp({email,password,options:{data:{name},emailRedirectTo:`${window.location.origin}/api/auth/callback?next=/minhas-compras`}}); if(error) throw error; setMessage("Confira seu e-mail para confirmar o cadastro."); } else if (mode === "recovery") { const { error }=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/recuperar-senha/nova`}); if(error) throw error; await fetch("/api/email-events/recovery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})}); setMessage("Enviamos o link de recuperação para seu e-mail."); } else { const { error }=await supabase.auth.updateUser({password}); if(error) throw error; setMessage("Senha atualizada. Você já pode acessar sua conta."); } } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível concluir a operação."); } finally { setLoading(false); } };
  const content = mode === "login" ? { title:"Entrar", copy:"Acesse seus materiais e acompanhe suas compras.", action:"Entrar" } : mode === "signup" ? { title:"Criar conta", copy:"Seu acesso será usado para liberar e guardar seus materiais.", action:"Criar conta" } : mode === "recovery" ? { title:"Recuperar senha",copy:"Vamos enviar um link seguro para você criar uma nova senha.",action:"Enviar link" } : { title:"Nova senha",copy:"Escolha uma senha nova para continuar acessando sua conta.",action:"Salvar nova senha" };
  return <form className="form panel" onSubmit={submit}><p className="eyebrow">Conta</p><h1 style={{ fontSize:42 }}>{content.title}</h1><p style={{ color:"var(--muted)",lineHeight:1.6 }}>{content.copy}</p>{mode === "signup" ? <label>Nome<input required className="input" value={name} onChange={(event)=>setName(event.target.value)} /></label> : null}{mode !== "new-password" ? <label>E-mail<input required type="email" className="input" value={email} onChange={(event)=>setEmail(event.target.value)} /></label> : null}{mode !== "recovery" ? <label>Senha<input required minLength={8} type="password" className="input" value={password} onChange={(event)=>setPassword(event.target.value)} /></label> : null}{error ? <p className="error">{error}</p> : null}{message ? <p className="success">{message}</p> : null}<button className="button" disabled={loading}>{loading ? "Aguarde..." : content.action}</button>{mode === "login" ? <><Link className="link" href="/recuperar-senha">Esqueci minha senha</Link><p style={{ fontSize:14 }}>Ainda não tem conta? <Link className="link" href="/cadastro">Criar conta</Link></p></> : null}{mode === "signup" ? <p style={{ fontSize:14 }}>Já tem conta? <Link className="link" href="/login">Entrar</Link></p> : null}</form>;
}
