import { createClient } from "@supabase/supabase-js";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!key)throw new Error('Configure NEXT_PUBLIC_SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY antes de executar o seed.');
const db=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});
const categories=[['Educação Infantil','educacao-infantil'],['Anos Iniciais','anos-iniciais'],['Datas Comemorativas','datas-comemorativas'],['Jogos','jogos'],['Kits','kits']];
const products: Array<[string,string,string,number]>=[['Colors Activities','colors-activities','Educação Infantil',890],['Numbers Activities','numbers-activities','Educação Infantil',990],['Back to School Kit','back-to-school-kit','Kits',2790],['English Games','english-games','Jogos',1890],['Halloween Activities','halloween-activities','Datas Comemorativas',1190]];
async function run(){for(const [name,slug] of categories){const {error}=await db.from('categories').upsert({name,slug,is_active:true},{onConflict:'slug'});if(error)throw error;}const {data:categoryRows,error:categoryError}=await db.from('categories').select('id,name');if(categoryError)throw categoryError;for(const [title,slug,categoryName,price] of products){const {data:product,error}=await db.from('products').upsert({title,slug,description:`Registro DEMO: ${title}. Substitua por conteúdo comercial antes da produção.`,short_description:'Material DEMO para validar o catálogo.',regular_price_cents:price,product_kind:title.includes('Kit')?'kit':'individual',status:'published',is_demo:true,published_at:new Date().toISOString()},{onConflict:'slug'}).select('id').single();if(error||!product)throw error??new Error('Produto DEMO não criado.');const category=categoryRows?.find(row=>row.name===categoryName);if(category)await db.from('product_categories').upsert({product_id:product.id,category_id:category.id},{onConflict:'product_id,category_id'});}}
void run().then(()=>console.log('Seed DEMO concluído.')).catch(error=>{console.error(error);process.exitCode=1;});
